name: Security Checks

on:
  push:
    branches:
      - main
      - PyGC
  pull_request:
    branches:
      - main
      - PyGC

jobs:
  security:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Bandit and Safety
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit for security linting
        run: |
          bandit -r bot/

      - name: Check for vulnerable dependencies with Safety
        run: |
          safety check --full-report
